### ISSUE TITLE
Error parsing jail list

### ISSUE THREAD

**Issue by d-stevens** [n1tr0-5urf3r/check_fail2ban#1]
The list of jails is not parsed correctly as there's a <tab> instead of a <space> in front of the first jail.
Tested with Fail2Ban v0.11.1.
The fix this issue i would suggest to replace the space in line 100 at the last sed-command with \s as this will remove all whitespace characters.

**Comment by n1tr0-5urf3r** [comment]
I never encountered this issue as it's parsed correctly, even though there is a tab in front of it. However, removing all whitespaces is generally a better idea. Thanks for the report, added in latest release
